name: Java CI with Maven for Bug API tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test Execution
        run: mvn -B -f pom.xml clean test
      - name: Get List of Files
        run: ls -a
      - name: What is in the target folder
        run: ls -a target
      - name: SureFire Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports
